---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: react-native
workflows:
  ios_simulator:
    description: |
      Installs dependencies.

      Next steps:
      - Add tests to your project and configure the workflow to run them.
      - Check out [Getting started with Expo apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-expo-apps.html).
    steps:
    - git-clone@8: {}
    - restore-npm-cache@3: {}
    - npm@3:
        title: npm install
        inputs:
        - command: install
    - save-npm-cache@1: {}
    - script@1:
        title: Exp prebuild
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
            set -o pipefail
            # debug log
            set -x

            # write your script here
            npx expo prebuild

            # or run a script from your repository, like:
            # bash ./path/to/script.sh
            # not just bash, e.g.:
            # ruby ./path/to/script.rb
    - restore-cocoapods-cache@3: {}
    - cocoapods-install@3:
        inputs:
        - source_root_path: ios
    - save-cocoapods-cache@1: {}
    - xcode-build-for-simulator@3:
        inputs:
        - configuration: release
        - xcodebuild_options: |-
            CODE_SIGN_IDENTITY=""
            CODE_SIGNING_REQUIRED=NO
            CODE_SIGNING_ALLOWED=NO
        - project_path: ios/Event-Registration.xcworkspace
        - scheme: Event-Registration
    - deploy-to-bitrise-io@2: {}
    triggers:
      push: []
      pull_request: []
  ios_dev:
    status_report_name: Executing <target_id> for <project_title>
    description: |
      Installs dependencies.

      Next steps:
      - Add tests to your project and configure the workflow to run them.
      - Check out [Getting started with Expo apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-expo-apps.html).
    steps:
    - git-clone@8: {}
    - restore-npm-cache@3: {}
    - npm@3:
        title: npm install
        inputs:
        - command: install
    - save-npm-cache@1: {}
    - script@1:
        title: Exp prebuild
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
            set -o pipefail
            # debug log
            set -x

            # write your script here
            npx expo prebuild

            # or run a script from your repository, like:
            # bash ./path/to/script.sh
            # not just bash, e.g.:
            # ruby ./path/to/script.rb
    - restore-cocoapods-cache@3: {}
    - cocoapods-install@3:
        inputs:
        - source_root_path: ios
    - save-cocoapods-cache@1: {}
    - certificate-and-profile-installer@1: {}
    - xcode-archive@6:
        inputs:
        - project_path: ios/Event-Registration.xcworkspace
        - scheme: Event-Registration
        - configuration: Release
        - verbose_log: 'yes'
        - xcodebuild_options: "CODE_SIGN_STYLE=\"Manual\"
            PROVISIONING_PROFILE=\"595cccbe-9879-4f9d-bf98-83124dd03643\"
            DEVELOPMENT_TEAM=\"DT2C2FZ7U2\"\ 

            CODE_SIGN_IDENTITY=\"iPhone Developer\""
    - deploy-to-bitrise-io@2: {}
    triggers:
      push: []
  android_dev:
    status_report_name: Executing <target_id> for <project_title>
    description: |
      Installs dependencies.

      Next steps:
      - Add tests to your project and configure the workflow to run them.
      - Check out [Getting started with Expo apps](https://devcenter.bitrise.io/en/getting-started/getting-started-with-expo-apps.html).
    steps:
    - git-clone@8: {}
    - restore-npm-cache@3: {}
    - npm@3:
        title: npm install
        inputs:
        - command: install
    - save-npm-cache@1: {}
    - script@1:
        title: Expo Prebuild
        inputs:
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
            set -o pipefail
            # debug log
            set -x

            # write your script here
            npx expo prebuild

            # or run a script from your repository, like:
            # bash ./path/to/script.sh
            # not just bash, e.g.:
            # ruby ./path/to/script.rb
    - android-build@1:
        inputs:
        - project_location: "$BITRISE_SOURCE_DIR/android"
        - module: app
        - variant: release
    - deploy-to-bitrise-io@2: {}
    triggers:
      push: []
meta:
  bitrise.io:
    stack: osx-xcode-26.4.x
    machine_type_id: g2.mac.large
app:
  envs:
  - PLATFORM: all
    opts:
      is_expand: false
pipelines:
  release:
    workflows:
      ios_dev: {}
      android_dev: {}
    triggers:
      pull_request:
      - target_branch: main
        label: release
    status_report_name: Executing <target_id> for <project_title>
